version: "16.6.7560931"
patch: "16.6"
manifest: "5f7c9c2142753174"
source: "rman"
date: "2026-03-20"
legacyBins: false
realms:
 - "BR1"
 - "EUN1"
 - "EUW1"
 - "JP1"
 - "KR"
 - "LA1"
 - "LA2"
 - "ME1"
 - "NA1"
 - "OC1"
 - "RU"
 - "SG2"
 - "TR1"
 - "TW2"
 - "VN2"
