version: "11.13.3821241"
patch: "11.13"
manifest: "114de324e0d901ab"
source: "rman"
date: "2021-06-17"
legacyBins: false
realms:
 - "BR1"
 - "EUN1"
 - "EUW1"
 - "JP1"
 - "KR"
 - "LA1"
 - "LA2"
 - "NA1"
 - "OC1"
 - "RU"
 - "TR1"
