version: "10.12.3253360"
patch: "10.12"
manifest: "9ce21ce89b7be659"
source: "rman"
date: "2020-06-16"
legacyBins: false
realms:
 - "BR1"
 - "EUN1"
 - "EUW1"
 - "JP1"
 - "KR"
 - "LA1"
 - "LA2"
 - "NA1"
 - "OC1"
 - "RU"
 - "TR1"
